SELECT * FROM GENERAL_LOG_EXECUCOES_SSIS ORDER BY ID DESC;

/* Executar TRUNCATE EM TODAS AS TABELAS DA RAW E HARMONIZED *
TRUNCATE TABLE CI_R_SCR010;
TRUNCATE TABLE CI_R_SCR020;
TRUNCATE TABLE CI_R_SCR030;
TRUNCATE TABLE CI_R_SYS_USR;
TRUNCATE TABLE CI_R_SAK010;
TRUNCATE TABLE CI_R_SAL010;
TRUNCATE TABLE CI_R_SYS_COMPANY;
TRUNCATE TABLE CI_R_CND010;

TRUNCATE TABLE CI_H_SCR010;
TRUNCATE TABLE CI_H_SCR020;
TRUNCATE TABLE CI_H_SCR030;
TRUNCATE TABLE CI_H_SYS_USR;
TRUNCATE TABLE CI_H_SAK010;
TRUNCATE TABLE CI_H_SAL010;
TRUNCATE TABLE CI_H_SYS_COMPANY;
TRUNCATE TABLE CI_H_CND010;

TRUNCATE TABLE GENERAL_LOG_EXECUCOES_SSIS;
*/

/* Executar SELECT COUNT(*) EM TODAS AS TABELAS DA RAW E HARMONIZED *
SELECT COUNT(*) AS CI_R_SCR010 FROM CI_R_SCR010;
SELECT COUNT(*) AS CI_R_SCR020 FROM CI_R_SCR020;
SELECT COUNT(*) AS CI_R_SCR030 FROM CI_R_SCR030;
SELECT COUNT(*) AS CI_R_SYS_USR FROM CI_R_SYS_USR;
SELECT COUNT(*) AS CI_R_SAK010 FROM CI_R_SAK010;
SELECT COUNT(*) AS CI_R_SAL010 FROM CI_R_SAL010;
SELECT COUNT(*) AS CI_R_SYS_COMPANY FROM CI_R_SYS_COMPANY;
SELECT COUNT(*) AS CI_R_CND010 FROM CI_R_CND010;

SELECT COUNT(*) AS CI_H_SCR010 FROM CI_H_SCR010;
SELECT COUNT(*) AS CI_H_SCR020 FROM CI_H_SCR020;
SELECT COUNT(*) AS CI_H_SCR030 FROM CI_H_SCR030;
SELECT COUNT(*) AS CI_H_SYS_USR FROM CI_H_SYS_USR;
SELECT COUNT(*) AS CI_H_SAK010 FROM CI_H_SAK010;
SELECT COUNT(*) AS CI_H_SAL010 FROM CI_H_SAL010;
SELECT COUNT(*) AS CI_H_SYS_COMPANY FROM CI_H_SYS_COMPANY;
SELECT COUNT(*) AS CI_H_CND010 FROM CI_H_CND010;
*/